/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package try4.module3;


import try4.utilities.Printer;

public class App {

    public static void main(String[] args) {
        Printer printer = new Printer("Print another thing");
        printer.print();
    }
}
