/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package try4.app;

//import org.apache.commons.text.WordUtils;
//import try4.utilities.Printer;

public class App {
//    public static void main(String[] args) throws Exception {
//
//        Printer printer = new Printer("Print this");
//        Printer.text = "testste";
//        Printer.print();
//    }

    public static void main(String[] args) {
        int a = 120;
        String b = "Strings";

        //в модуле 1 чекаем комменты, чисто база
        System.out.print(a + " " +b);
    }
}
